// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: user.proto

// proto 包名

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应
type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"` //根据邮箱验证码创建账号
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`   //验证码
	AvatarName    string                 `protobuf:"bytes,6,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"` //头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CreateUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateUserReq) GetAvatarName() string {
	if x != nil {
		return x.AvatarName
	}
	return ""
}

func (x *CreateUserReq) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetUserByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdReq) Reset() {
	*x = GetUserByIdReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdReq) ProtoMessage() {}

func (x *GetUserByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdReq.ProtoReflect.Descriptor instead.
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *UserInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResp) Reset() {
	*x = GetUserByIdResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResp) ProtoMessage() {}

func (x *GetUserByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResp.ProtoReflect.Descriptor instead.
func (*GetUserByIdResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUserByIdResp) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverName  string                 `protobuf:"bytes,1,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone string                 `protobuf:"bytes,2,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	DetailAddress string                 `protobuf:"bytes,6,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"`
	IsDefault     int32                  `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"` //是否默认地址
	AddrId        int64                  `protobuf:"varint,8,opt,name=addr_id,json=addrId,proto3" json:"addr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *Address) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *Address) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

func (x *Address) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *Address) GetAddrId() int64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

type GetAddrsByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddrsByIdReq) Reset() {
	*x = GetAddrsByIdReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddrsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrsByIdReq) ProtoMessage() {}

func (x *GetAddrsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrsByIdReq.ProtoReflect.Descriptor instead.
func (*GetAddrsByIdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetAddrsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAddrsByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          []*Address             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddrsByIdResp) Reset() {
	*x = GetAddrsByIdResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddrsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrsByIdResp) ProtoMessage() {}

func (x *GetAddrsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrsByIdResp.ProtoReflect.Descriptor instead.
func (*GetAddrsByIdResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetAddrsByIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetAddrsByIdResp) GetData() []*Address {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateAddrsByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          *Address               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddrsByIdReq) Reset() {
	*x = CreateAddrsByIdReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddrsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddrsByIdReq) ProtoMessage() {}

func (x *CreateAddrsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddrsByIdReq.ProtoReflect.Descriptor instead.
func (*CreateAddrsByIdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAddrsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAddrsByIdReq) GetAddr() *Address {
	if x != nil {
		return x.Addr
	}
	return nil
}

type CreateAddrsByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddrsByIdResp) Reset() {
	*x = CreateAddrsByIdResp{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddrsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddrsByIdResp) ProtoMessage() {}

func (x *CreateAddrsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddrsByIdResp.ProtoReflect.Descriptor instead.
func (*CreateAddrsByIdResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAddrsByIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type ChangeUserPwdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewPwd        string                 `protobuf:"bytes,2,opt,name=new_pwd,json=newPwd,proto3" json:"new_pwd,omitempty"`
	OldPwd        string                 `protobuf:"bytes,3,opt,name=old_pwd,json=oldPwd,proto3" json:"old_pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPwdReq) Reset() {
	*x = ChangeUserPwdReq{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPwdReq) ProtoMessage() {}

func (x *ChangeUserPwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPwdReq.ProtoReflect.Descriptor instead.
func (*ChangeUserPwdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeUserPwdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeUserPwdReq) GetNewPwd() string {
	if x != nil {
		return x.NewPwd
	}
	return ""
}

func (x *ChangeUserPwdReq) GetOldPwd() string {
	if x != nil {
		return x.OldPwd
	}
	return ""
}

type ChangeUserPwdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPwdResp) Reset() {
	*x = ChangeUserPwdResp{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPwdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPwdResp) ProtoMessage() {}

func (x *ChangeUserPwdResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPwdResp.ProtoReflect.Descriptor instead.
func (*ChangeUserPwdResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeUserPwdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type ChangeUserNicknameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserNicknameReq) Reset() {
	*x = ChangeUserNicknameReq{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNicknameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNicknameReq) ProtoMessage() {}

func (x *ChangeUserNicknameReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNicknameReq.ProtoReflect.Descriptor instead.
func (*ChangeUserNicknameReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeUserNicknameReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeUserNicknameReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type ChangeUserNicknameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserNicknameResp) Reset() {
	*x = ChangeUserNicknameResp{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNicknameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNicknameResp) ProtoMessage() {}

func (x *ChangeUserNicknameResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNicknameResp.ProtoReflect.Descriptor instead.
func (*ChangeUserNicknameResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeUserNicknameResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type DeleteAddrByAddrIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddrByAddrIdReq) Reset() {
	*x = DeleteAddrByAddrIdReq{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddrByAddrIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddrByAddrIdReq) ProtoMessage() {}

func (x *DeleteAddrByAddrIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddrByAddrIdReq.ProtoReflect.Descriptor instead.
func (*DeleteAddrByAddrIdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteAddrByAddrIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAddrByAddrIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddrByAddrIdResp) Reset() {
	*x = DeleteAddrByAddrIdResp{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddrByAddrIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddrByAddrIdResp) ProtoMessage() {}

func (x *DeleteAddrByAddrIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddrByAddrIdResp.ProtoReflect.Descriptor instead.
func (*DeleteAddrByAddrIdResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAddrByAddrIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type IncreaseBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Incr          float64                `protobuf:"fixed64,2,opt,name=incr,proto3" json:"incr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseBalanceReq) Reset() {
	*x = IncreaseBalanceReq{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseBalanceReq) ProtoMessage() {}

func (x *IncreaseBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseBalanceReq.ProtoReflect.Descriptor instead.
func (*IncreaseBalanceReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *IncreaseBalanceReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncreaseBalanceReq) GetIncr() float64 {
	if x != nil {
		return x.Incr
	}
	return 0
}

type IncreaseBalanceResq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseBalanceResq) Reset() {
	*x = IncreaseBalanceResq{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseBalanceResq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseBalanceResq) ProtoMessage() {}

func (x *IncreaseBalanceResq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseBalanceResq.ProtoReflect.Descriptor instead.
func (*IncreaseBalanceResq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *IncreaseBalanceResq) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetEmailCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailCodeReq) Reset() {
	*x = GetEmailCodeReq{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailCodeReq) ProtoMessage() {}

func (x *GetEmailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailCodeReq.ProtoReflect.Descriptor instead.
func (*GetEmailCodeReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetEmailCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetEmailCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailCodeResp) Reset() {
	*x = GetEmailCodeResp{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailCodeResp) ProtoMessage() {}

func (x *GetEmailCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailCodeResp.ProtoReflect.Descriptor instead.
func (*GetEmailCodeResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetEmailCodeResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type FrozenBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SkProductId   int64                  `protobuf:"varint,2,opt,name=skProductId,proto3" json:"skProductId,omitempty"`
	OrderNo       int64                  `protobuf:"varint,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrozenBalanceReq) Reset() {
	*x = FrozenBalanceReq{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrozenBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrozenBalanceReq) ProtoMessage() {}

func (x *FrozenBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrozenBalanceReq.ProtoReflect.Descriptor instead.
func (*FrozenBalanceReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *FrozenBalanceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FrozenBalanceReq) GetSkProductId() int64 {
	if x != nil {
		return x.SkProductId
	}
	return 0
}

func (x *FrozenBalanceReq) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

type FrozenBalanceResq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrozenBalanceResq) Reset() {
	*x = FrozenBalanceResq{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrozenBalanceResq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrozenBalanceResq) ProtoMessage() {}

func (x *FrozenBalanceResq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrozenBalanceResq.ProtoReflect.Descriptor instead.
func (*FrozenBalanceResq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *FrozenBalanceResq) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FrozenBalanceResq) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *FrozenBalanceResq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type ReduceFrozenBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceFrozenBalanceReq) Reset() {
	*x = ReduceFrozenBalanceReq{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceFrozenBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceFrozenBalanceReq) ProtoMessage() {}

func (x *ReduceFrozenBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceFrozenBalanceReq.ProtoReflect.Descriptor instead.
func (*ReduceFrozenBalanceReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *ReduceFrozenBalanceReq) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *ReduceFrozenBalanceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReduceFrozenBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceFrozenBalanceResp) Reset() {
	*x = ReduceFrozenBalanceResp{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceFrozenBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceFrozenBalanceResp) ProtoMessage() {}

func (x *ReduceFrozenBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceFrozenBalanceResp.ProtoReflect.Descriptor instead.
func (*ReduceFrozenBalanceResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *ReduceFrozenBalanceResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetFrozenInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrozenInfoReq) Reset() {
	*x = GetFrozenInfoReq{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrozenInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrozenInfoReq) ProtoMessage() {}

func (x *GetFrozenInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrozenInfoReq.ProtoReflect.Descriptor instead.
func (*GetFrozenInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *GetFrozenInfoReq) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

type GetFrozenInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrozenInfoResp) Reset() {
	*x = GetFrozenInfoResp{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrozenInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrozenInfoResp) ProtoMessage() {}

func (x *GetFrozenInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrozenInfoResp.ProtoReflect.Descriptor instead.
func (*GetFrozenInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *GetFrozenInfoResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Pwd           string                 `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *LoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	NickName      string                 `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *LoginResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginResp) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type JwtAuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtAuthReq) Reset() {
	*x = JwtAuthReq{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtAuthReq) ProtoMessage() {}

func (x *JwtAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtAuthReq.ProtoReflect.Descriptor instead.
func (*JwtAuthReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *JwtAuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtAuthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtAuthResp) Reset() {
	*x = JwtAuthResp{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtAuthResp) ProtoMessage() {}

func (x *JwtAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtAuthResp.ProtoReflect.Descriptor instead.
func (*JwtAuthResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *JwtAuthResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *JwtAuthResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xc8\x01\n" +
	"\rCreateUserReq\x12\x1b\n" +
	"\tnick_name\x18\x01 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1f\n" +
	"\vavatar_name\x18\x06 \x01(\tR\n" +
	"avatarName\x12\x16\n" +
	"\x06avatar\x18\a \x01(\fR\x06avatar\"4\n" +
	"\x0eCreateUserResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"n\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\" \n" +
	"\x0eGetUserByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Y\n" +
	"\x0fGetUserByIdResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\x12\"\n" +
	"\x04data\x18\x02 \x01(\v2\x0e.user.UserInfoR\x04data\"\x80\x02\n" +
	"\aAddress\x12#\n" +
	"\rreceiver_name\x18\x01 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x02 \x01(\tR\rreceiverPhone\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\x12%\n" +
	"\x0edetail_address\x18\x06 \x01(\tR\rdetailAddress\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\x05R\tisDefault\x12\x17\n" +
	"\aaddr_id\x18\b \x01(\x03R\x06addrId\"!\n" +
	"\x0fGetAddrsByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Y\n" +
	"\x10GetAddrsByIdResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\x12!\n" +
	"\x04data\x18\x02 \x03(\v2\r.user.AddressR\x04data\"G\n" +
	"\x12CreateAddrsByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\x04addr\x18\x02 \x01(\v2\r.user.AddressR\x04addr\"9\n" +
	"\x13CreateAddrsByIdResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"T\n" +
	"\x10ChangeUserPwdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\anew_pwd\x18\x02 \x01(\tR\x06newPwd\x12\x17\n" +
	"\aold_pwd\x18\x03 \x01(\tR\x06oldPwd\"7\n" +
	"\x11ChangeUserPwdResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"B\n" +
	"\x15ChangeUserNicknameReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"<\n" +
	"\x16ChangeUserNicknameResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"'\n" +
	"\x15DeleteAddrByAddrIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x16DeleteAddrByAddrIdResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"8\n" +
	"\x12IncreaseBalanceReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04incr\x18\x02 \x01(\x01R\x04incr\"9\n" +
	"\x13IncreaseBalanceResq\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"'\n" +
	"\x0fGetEmailCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"6\n" +
	"\x10GetEmailCodeResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"f\n" +
	"\x10FrozenBalanceReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vskProductId\x18\x02 \x01(\x03R\vskProductId\x12\x18\n" +
	"\aorderNo\x18\x03 \x01(\x03R\aorderNo\"y\n" +
	"\x11FrozenBalanceResq\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\x12 \n" +
	"\vtotalAmount\x18\x02 \x01(\tR\vtotalAmount\x12\x1e\n" +
	"\n" +
	"MerchantId\x18\x03 \x01(\x03R\n" +
	"MerchantId\"J\n" +
	"\x16ReduceFrozenBalanceReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"=\n" +
	"\x17ReduceFrozenBalanceResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\",\n" +
	"\x10GetFrozenInfoReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\"7\n" +
	"\x11GetFrozenInfoResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\"8\n" +
	"\bLoginReq\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x10\n" +
	"\x03pwd\x18\x02 \x01(\tR\x03pwd\"y\n" +
	"\tLoginResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickName\x18\x04 \x01(\tR\bnickName\"\"\n" +
	"\n" +
	"JwtAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\vJwtAuthResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.user.BaseRespR\x04base\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId2\xfe\a\n" +
	"\x04User\x127\n" +
	"\n" +
	"CreateUser\x12\x13.user.CreateUserReq\x1a\x14.user.CreateUserResp\x12:\n" +
	"\vGetUserById\x12\x14.user.GetUserByIdReq\x1a\x15.user.GetUserByIdResp\x12@\n" +
	"\rChangeUserPwd\x12\x16.user.ChangeUserPwdReq\x1a\x17.user.ChangeUserPwdResp\x12O\n" +
	"\x12ChangeUserNickname\x12\x1b.user.ChangeUserNicknameReq\x1a\x1c.user.ChangeUserNicknameResp\x12J\n" +
	"\x13CreateUserAddrsById\x12\x18.user.CreateAddrsByIdReq\x1a\x19.user.CreateAddrsByIdResp\x12A\n" +
	"\x10GetUserAddrsById\x12\x15.user.GetAddrsByIdReq\x1a\x16.user.GetAddrsByIdResp\x12O\n" +
	"\x12DeleteAddrByAddrId\x12\x1b.user.DeleteAddrByAddrIdReq\x1a\x1c.user.DeleteAddrByAddrIdResp\x12F\n" +
	"\x0fIncreaseBalance\x12\x18.user.IncreaseBalanceReq\x1a\x19.user.IncreaseBalanceResq\x12=\n" +
	"\fGetEmailCode\x12\x15.user.GetEmailCodeReq\x1a\x16.user.GetEmailCodeResp\x12@\n" +
	"\rFrozenBalance\x12\x16.user.FrozenBalanceReq\x1a\x17.user.FrozenBalanceResq\x12R\n" +
	"\x13ReduceFrozenBalance\x12\x1c.user.ReduceFrozenBalanceReq\x1a\x1d.user.ReduceFrozenBalanceResp\x12U\n" +
	"\x16ComReduceFrozenBalance\x12\x1c.user.ReduceFrozenBalanceReq\x1a\x1d.user.ReduceFrozenBalanceResp\x12@\n" +
	"\rGetFrozenInfo\x12\x16.user.GetFrozenInfoReq\x1a\x17.user.GetFrozenInfoResp\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x12.\n" +
	"\aJwtAuth\x12\x10.user.JwtAuthReq\x1a\x11.user.JwtAuthRespB\x04Z\x02./b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_user_proto_goTypes = []any{
	(*BaseResp)(nil),                // 0: user.BaseResp
	(*CreateUserReq)(nil),           // 1: user.CreateUserReq
	(*CreateUserResp)(nil),          // 2: user.CreateUserResp
	(*UserInfo)(nil),                // 3: user.UserInfo
	(*GetUserByIdReq)(nil),          // 4: user.GetUserByIdReq
	(*GetUserByIdResp)(nil),         // 5: user.GetUserByIdResp
	(*Address)(nil),                 // 6: user.Address
	(*GetAddrsByIdReq)(nil),         // 7: user.GetAddrsByIdReq
	(*GetAddrsByIdResp)(nil),        // 8: user.GetAddrsByIdResp
	(*CreateAddrsByIdReq)(nil),      // 9: user.CreateAddrsByIdReq
	(*CreateAddrsByIdResp)(nil),     // 10: user.CreateAddrsByIdResp
	(*ChangeUserPwdReq)(nil),        // 11: user.ChangeUserPwdReq
	(*ChangeUserPwdResp)(nil),       // 12: user.ChangeUserPwdResp
	(*ChangeUserNicknameReq)(nil),   // 13: user.ChangeUserNicknameReq
	(*ChangeUserNicknameResp)(nil),  // 14: user.ChangeUserNicknameResp
	(*DeleteAddrByAddrIdReq)(nil),   // 15: user.DeleteAddrByAddrIdReq
	(*DeleteAddrByAddrIdResp)(nil),  // 16: user.DeleteAddrByAddrIdResp
	(*IncreaseBalanceReq)(nil),      // 17: user.IncreaseBalanceReq
	(*IncreaseBalanceResq)(nil),     // 18: user.IncreaseBalanceResq
	(*GetEmailCodeReq)(nil),         // 19: user.GetEmailCodeReq
	(*GetEmailCodeResp)(nil),        // 20: user.GetEmailCodeResp
	(*FrozenBalanceReq)(nil),        // 21: user.FrozenBalanceReq
	(*FrozenBalanceResq)(nil),       // 22: user.FrozenBalanceResq
	(*ReduceFrozenBalanceReq)(nil),  // 23: user.ReduceFrozenBalanceReq
	(*ReduceFrozenBalanceResp)(nil), // 24: user.ReduceFrozenBalanceResp
	(*GetFrozenInfoReq)(nil),        // 25: user.GetFrozenInfoReq
	(*GetFrozenInfoResp)(nil),       // 26: user.GetFrozenInfoResp
	(*LoginReq)(nil),                // 27: user.LoginReq
	(*LoginResp)(nil),               // 28: user.LoginResp
	(*JwtAuthReq)(nil),              // 29: user.JwtAuthReq
	(*JwtAuthResp)(nil),             // 30: user.JwtAuthResp
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.CreateUserResp.base:type_name -> user.BaseResp
	0,  // 1: user.GetUserByIdResp.base:type_name -> user.BaseResp
	3,  // 2: user.GetUserByIdResp.data:type_name -> user.UserInfo
	0,  // 3: user.GetAddrsByIdResp.base:type_name -> user.BaseResp
	6,  // 4: user.GetAddrsByIdResp.data:type_name -> user.Address
	6,  // 5: user.CreateAddrsByIdReq.addr:type_name -> user.Address
	0,  // 6: user.CreateAddrsByIdResp.base:type_name -> user.BaseResp
	0,  // 7: user.ChangeUserPwdResp.base:type_name -> user.BaseResp
	0,  // 8: user.ChangeUserNicknameResp.base:type_name -> user.BaseResp
	0,  // 9: user.DeleteAddrByAddrIdResp.base:type_name -> user.BaseResp
	0,  // 10: user.IncreaseBalanceResq.base:type_name -> user.BaseResp
	0,  // 11: user.GetEmailCodeResp.base:type_name -> user.BaseResp
	0,  // 12: user.FrozenBalanceResq.base:type_name -> user.BaseResp
	0,  // 13: user.ReduceFrozenBalanceResp.base:type_name -> user.BaseResp
	0,  // 14: user.GetFrozenInfoResp.base:type_name -> user.BaseResp
	0,  // 15: user.LoginResp.base:type_name -> user.BaseResp
	0,  // 16: user.JwtAuthResp.base:type_name -> user.BaseResp
	1,  // 17: user.User.CreateUser:input_type -> user.CreateUserReq
	4,  // 18: user.User.GetUserById:input_type -> user.GetUserByIdReq
	11, // 19: user.User.ChangeUserPwd:input_type -> user.ChangeUserPwdReq
	13, // 20: user.User.ChangeUserNickname:input_type -> user.ChangeUserNicknameReq
	9,  // 21: user.User.CreateUserAddrsById:input_type -> user.CreateAddrsByIdReq
	7,  // 22: user.User.GetUserAddrsById:input_type -> user.GetAddrsByIdReq
	15, // 23: user.User.DeleteAddrByAddrId:input_type -> user.DeleteAddrByAddrIdReq
	17, // 24: user.User.IncreaseBalance:input_type -> user.IncreaseBalanceReq
	19, // 25: user.User.GetEmailCode:input_type -> user.GetEmailCodeReq
	21, // 26: user.User.FrozenBalance:input_type -> user.FrozenBalanceReq
	23, // 27: user.User.ReduceFrozenBalance:input_type -> user.ReduceFrozenBalanceReq
	23, // 28: user.User.ComReduceFrozenBalance:input_type -> user.ReduceFrozenBalanceReq
	25, // 29: user.User.GetFrozenInfo:input_type -> user.GetFrozenInfoReq
	27, // 30: user.User.Login:input_type -> user.LoginReq
	29, // 31: user.User.JwtAuth:input_type -> user.JwtAuthReq
	2,  // 32: user.User.CreateUser:output_type -> user.CreateUserResp
	5,  // 33: user.User.GetUserById:output_type -> user.GetUserByIdResp
	12, // 34: user.User.ChangeUserPwd:output_type -> user.ChangeUserPwdResp
	14, // 35: user.User.ChangeUserNickname:output_type -> user.ChangeUserNicknameResp
	10, // 36: user.User.CreateUserAddrsById:output_type -> user.CreateAddrsByIdResp
	8,  // 37: user.User.GetUserAddrsById:output_type -> user.GetAddrsByIdResp
	16, // 38: user.User.DeleteAddrByAddrId:output_type -> user.DeleteAddrByAddrIdResp
	18, // 39: user.User.IncreaseBalance:output_type -> user.IncreaseBalanceResq
	20, // 40: user.User.GetEmailCode:output_type -> user.GetEmailCodeResp
	22, // 41: user.User.FrozenBalance:output_type -> user.FrozenBalanceResq
	24, // 42: user.User.ReduceFrozenBalance:output_type -> user.ReduceFrozenBalanceResp
	24, // 43: user.User.ComReduceFrozenBalance:output_type -> user.ReduceFrozenBalanceResp
	26, // 44: user.User.GetFrozenInfo:output_type -> user.GetFrozenInfoResp
	28, // 45: user.User.Login:output_type -> user.LoginResp
	30, // 46: user.User.JwtAuth:output_type -> user.JwtAuthResp
	32, // [32:47] is the sub-list for method output_type
	17, // [17:32] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
