// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: order.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	AddrId        int64                  `protobuf:"varint,2,opt,name=addrId,proto3" json:"addrId,omitempty"`
	SkProduckId   int64                  `protobuf:"varint,3,opt,name=skProduckId,proto3" json:"skProduckId,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` //订单状态：0-待支付，1-已支付，2-已发货，3-已完成，4-已取消，5-超时关闭
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInfo) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *OrderInfo) GetAddrId() int64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

func (x *OrderInfo) GetSkProduckId() int64 {
	if x != nil {
		return x.SkProduckId
	}
	return 0
}

func (x *OrderInfo) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderInfo) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *OrderInfo) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderInfo) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type OrderListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	SkProduckId   int64                  `protobuf:"varint,2,opt,name=skProduckId,proto3" json:"skProduckId,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,4,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,5,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` //订单状态：0-待支付，1-已支付，2-已发货，3-已完成，4-已取消，5-超时关闭
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListInfo) Reset() {
	*x = OrderListInfo{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListInfo) ProtoMessage() {}

func (x *OrderListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListInfo.ProtoReflect.Descriptor instead.
func (*OrderListInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderListInfo) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *OrderListInfo) GetSkProduckId() int64 {
	if x != nil {
		return x.SkProduckId
	}
	return 0
}

func (x *OrderListInfo) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderListInfo) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *OrderListInfo) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *OrderListInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderListInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderListInfo) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Info          *OrderInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResp) Reset() {
	*x = GetOrderResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResp) ProtoMessage() {}

func (x *GetOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResp.ProtoReflect.Descriptor instead.
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetOrderResp) GetInfo() *OrderInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListReq) Reset() {
	*x = GetOrderListReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListReq) ProtoMessage() {}

func (x *GetOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListReq.ProtoReflect.Descriptor instead.
func (*GetOrderListReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*OrderListInfo       `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListResp) Reset() {
	*x = GetOrderListResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListResp) ProtoMessage() {}

func (x *GetOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListResp.ProtoReflect.Descriptor instead.
func (*GetOrderListResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderListResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetOrderListResp) GetList() []*OrderListInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xc7\x02\n" +
	"\tOrderInfo\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\x12\x16\n" +
	"\x06addrId\x18\x02 \x01(\x03R\x06addrId\x12 \n" +
	"\vskProduckId\x18\x03 \x01(\x03R\vskProduckId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x05 \x01(\tR\tunitPrice\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\texpire_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"\xb3\x02\n" +
	"\rOrderListInfo\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\x12 \n" +
	"\vskProduckId\x18\x02 \x01(\x03R\vskProduckId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x04 \x01(\tR\tunitPrice\x12 \n" +
	"\vtotalAmount\x18\x05 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\texpire_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"?\n" +
	"\vGetOrderReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"Y\n" +
	"\fGetOrderResp\x12#\n" +
	"\x04base\x18\x01 \x01(\v2\x0f.order.BaseRespR\x04base\x12$\n" +
	"\x04info\x18\x02 \x01(\v2\x10.order.OrderInfoR\x04info\"S\n" +
	"\x0fGetOrderListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"a\n" +
	"\x10GetOrderListResp\x12#\n" +
	"\x04base\x18\x01 \x01(\v2\x0f.order.BaseRespR\x04base\x12(\n" +
	"\x04List\x18\x02 \x03(\v2\x14.order.OrderListInfoR\x04List2}\n" +
	"\x05Order\x123\n" +
	"\bGetOrder\x12\x12.order.GetOrderReq\x1a\x13.order.GetOrderResp\x12?\n" +
	"\fGetOrderList\x12\x16.order.GetOrderListReq\x1a\x17.order.GetOrderListRespB\x04Z\x02./b\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_proto_goTypes = []any{
	(*BaseResp)(nil),              // 0: order.BaseResp
	(*OrderInfo)(nil),             // 1: order.OrderInfo
	(*OrderListInfo)(nil),         // 2: order.OrderListInfo
	(*GetOrderReq)(nil),           // 3: order.GetOrderReq
	(*GetOrderResp)(nil),          // 4: order.GetOrderResp
	(*GetOrderListReq)(nil),       // 5: order.GetOrderListReq
	(*GetOrderListResp)(nil),      // 6: order.GetOrderListResp
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	7,  // 0: order.OrderInfo.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: order.OrderInfo.expire_at:type_name -> google.protobuf.Timestamp
	7,  // 2: order.OrderListInfo.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: order.OrderListInfo.expire_at:type_name -> google.protobuf.Timestamp
	0,  // 4: order.GetOrderResp.base:type_name -> order.BaseResp
	1,  // 5: order.GetOrderResp.info:type_name -> order.OrderInfo
	0,  // 6: order.GetOrderListResp.base:type_name -> order.BaseResp
	2,  // 7: order.GetOrderListResp.List:type_name -> order.OrderListInfo
	3,  // 8: order.Order.GetOrder:input_type -> order.GetOrderReq
	5,  // 9: order.Order.GetOrderList:input_type -> order.GetOrderListReq
	4,  // 10: order.Order.GetOrder:output_type -> order.GetOrderResp
	6,  // 11: order.Order.GetOrderList:output_type -> order.GetOrderListResp
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
