// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: product.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应
type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateProductReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       uint64                 `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc             string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	CoverImageSuffix string                 `protobuf:"bytes,4,opt,name=cover_image_suffix,json=coverImageSuffix,proto3" json:"cover_image_suffix,omitempty"`
	CoverImage       []byte                 `protobuf:"bytes,5,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Price            string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Stock            uint64                 `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Status           int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReq) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateProductReq) GetCoverImageSuffix() string {
	if x != nil {
		return x.CoverImageSuffix
	}
	return ""
}

func (x *CreateProductReq) GetCoverImage() []byte {
	if x != nil {
		return x.CoverImage
	}
	return nil
}

func (x *CreateProductReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateProductReq) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type CreateSKEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    uint64                 `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSKEventReq) Reset() {
	*x = CreateSKEventReq{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSKEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSKEventReq) ProtoMessage() {}

func (x *CreateSKEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSKEventReq.ProtoReflect.Descriptor instead.
func (*CreateSKEventReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSKEventReq) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateSKEventReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSKEventReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateSKEventReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateSKEventReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateSKEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSKEventResp) Reset() {
	*x = CreateSKEventResp{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSKEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSKEventResp) ProtoMessage() {}

func (x *CreateSKEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSKEventResp.ProtoReflect.Descriptor instead.
func (*CreateSKEventResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSKEventResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type CreateSKProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SeckillPrice  string                 `protobuf:"bytes,3,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	SeckillStock  uint64                 `protobuf:"varint,4,opt,name=seckill_stock,json=seckillStock,proto3" json:"seckill_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSKProductReq) Reset() {
	*x = CreateSKProductReq{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSKProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSKProductReq) ProtoMessage() {}

func (x *CreateSKProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSKProductReq.ProtoReflect.Descriptor instead.
func (*CreateSKProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSKProductReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateSKProductReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateSKProductReq) GetSeckillPrice() string {
	if x != nil {
		return x.SeckillPrice
	}
	return ""
}

func (x *CreateSKProductReq) GetSeckillStock() uint64 {
	if x != nil {
		return x.SeckillStock
	}
	return 0
}

type CreateSKProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSKProductResp) Reset() {
	*x = CreateSKProductResp{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSKProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSKProductResp) ProtoMessage() {}

func (x *CreateSKProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSKProductResp.ProtoReflect.Descriptor instead.
func (*CreateSKProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSKProductResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type SKProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	EvId          int64                  `protobuf:"varint,2,opt,name=EvId,proto3" json:"EvId,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	SeckillPrice  string                 `protobuf:"bytes,4,opt,name=SeckillPrice,proto3" json:"SeckillPrice,omitempty"`
	SeckillStock  int64                  `protobuf:"varint,5,opt,name=SeckillStock,proto3" json:"SeckillStock,omitempty"`
	MerchantId    int64                  `protobuf:"varint,6,opt,name=MerchantId,proto3" json:"MerchantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKProductInfo) Reset() {
	*x = SKProductInfo{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKProductInfo) ProtoMessage() {}

func (x *SKProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKProductInfo.ProtoReflect.Descriptor instead.
func (*SKProductInfo) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *SKProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SKProductInfo) GetEvId() int64 {
	if x != nil {
		return x.EvId
	}
	return 0
}

func (x *SKProductInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SKProductInfo) GetSeckillPrice() string {
	if x != nil {
		return x.SeckillPrice
	}
	return ""
}

func (x *SKProductInfo) GetSeckillStock() int64 {
	if x != nil {
		return x.SeckillStock
	}
	return 0
}

func (x *SKProductInfo) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type GetSKProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SKProductID   int64                  `protobuf:"varint,1,opt,name=SKProductID,proto3" json:"SKProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKProductReq) Reset() {
	*x = GetSKProductReq{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKProductReq) ProtoMessage() {}

func (x *GetSKProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKProductReq.ProtoReflect.Descriptor instead.
func (*GetSKProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetSKProductReq) GetSKProductID() int64 {
	if x != nil {
		return x.SKProductID
	}
	return 0
}

type GetSKProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Info          *SKProductInfo         `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKProductResp) Reset() {
	*x = GetSKProductResp{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKProductResp) ProtoMessage() {}

func (x *GetSKProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKProductResp.ProtoReflect.Descriptor instead.
func (*GetSKProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *GetSKProductResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetSKProductResp) GetInfo() *SKProductInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetSKEvStatusByPIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PId           int64                  `protobuf:"varint,1,opt,name=PId,proto3" json:"PId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKEvStatusByPIdReq) Reset() {
	*x = GetSKEvStatusByPIdReq{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKEvStatusByPIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKEvStatusByPIdReq) ProtoMessage() {}

func (x *GetSKEvStatusByPIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKEvStatusByPIdReq.ProtoReflect.Descriptor instead.
func (*GetSKEvStatusByPIdReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *GetSKEvStatusByPIdReq) GetPId() int64 {
	if x != nil {
		return x.PId
	}
	return 0
}

type GetSKEvStatusByPIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` //活动状态：1=未开始，2=进行中，3=已结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKEvStatusByPIdResp) Reset() {
	*x = GetSKEvStatusByPIdResp{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKEvStatusByPIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKEvStatusByPIdResp) ProtoMessage() {}

func (x *GetSKEvStatusByPIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKEvStatusByPIdResp.ProtoReflect.Descriptor instead.
func (*GetSKEvStatusByPIdResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *GetSKEvStatusByPIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetSKEvStatusByPIdResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetSKEvStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvId          int64                  `protobuf:"varint,1,opt,name=EvId,proto3" json:"EvId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKEvStatusReq) Reset() {
	*x = GetSKEvStatusReq{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKEvStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKEvStatusReq) ProtoMessage() {}

func (x *GetSKEvStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKEvStatusReq.ProtoReflect.Descriptor instead.
func (*GetSKEvStatusReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *GetSKEvStatusReq) GetEvId() int64 {
	if x != nil {
		return x.EvId
	}
	return 0
}

type GetSKEvStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` //活动状态：1=未开始，2=进行中，3=已结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKEvStatusResp) Reset() {
	*x = GetSKEvStatusResp{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKEvStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKEvStatusResp) ProtoMessage() {}

func (x *GetSKEvStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKEvStatusResp.ProtoReflect.Descriptor instead.
func (*GetSKEvStatusResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *GetSKEvStatusResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetSKEvStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReduceSkProductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SKProductId   int64                  `protobuf:"varint,1,opt,name=SKProductId,proto3" json:"SKProductId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceSkProductStockReq) Reset() {
	*x = ReduceSkProductStockReq{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceSkProductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSkProductStockReq) ProtoMessage() {}

func (x *ReduceSkProductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSkProductStockReq.ProtoReflect.Descriptor instead.
func (*ReduceSkProductStockReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *ReduceSkProductStockReq) GetSKProductId() int64 {
	if x != nil {
		return x.SKProductId
	}
	return 0
}

type ReduceSkProductStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceSkProductStockResp) Reset() {
	*x = ReduceSkProductStockResp{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceSkProductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSkProductStockResp) ProtoMessage() {}

func (x *ReduceSkProductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSkProductStockResp.ProtoReflect.Descriptor instead.
func (*ReduceSkProductStockResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *ReduceSkProductStockResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xee\x01\n" +
	"\x10CreateProductReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x04R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12,\n" +
	"\x12cover_image_suffix\x18\x04 \x01(\tR\x10coverImageSuffix\x12\x1f\n" +
	"\vcover_image\x18\x05 \x01(\fR\n" +
	"coverImage\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x14\n" +
	"\x05stock\x18\a \x01(\x04R\x05stock\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\":\n" +
	"\x11CreateProductResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base\"\xd1\x01\n" +
	"\x10CreateSKEventReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x04R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\":\n" +
	"\x11CreateSKEventResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base\"\x98\x01\n" +
	"\x12CreateSKProductReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12#\n" +
	"\rseckill_price\x18\x03 \x01(\tR\fseckillPrice\x12#\n" +
	"\rseckill_stock\x18\x04 \x01(\x04R\fseckillStock\"<\n" +
	"\x13CreateSKProductResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base\"\xb9\x01\n" +
	"\rSKProductInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x12\n" +
	"\x04EvId\x18\x02 \x01(\x03R\x04EvId\x12\x1c\n" +
	"\tProductId\x18\x03 \x01(\x03R\tProductId\x12\"\n" +
	"\fSeckillPrice\x18\x04 \x01(\tR\fSeckillPrice\x12\"\n" +
	"\fSeckillStock\x18\x05 \x01(\x03R\fSeckillStock\x12\x1e\n" +
	"\n" +
	"MerchantId\x18\x06 \x01(\x03R\n" +
	"MerchantId\"3\n" +
	"\x0fGetSKProductReq\x12 \n" +
	"\vSKProductID\x18\x01 \x01(\x03R\vSKProductID\"e\n" +
	"\x10GetSKProductResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base\x12*\n" +
	"\x04info\x18\x02 \x01(\v2\x16.product.SKProductInfoR\x04info\")\n" +
	"\x15GetSKEvStatusByPIdReq\x12\x10\n" +
	"\x03PId\x18\x01 \x01(\x03R\x03PId\"W\n" +
	"\x16GetSKEvStatusByPIdResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"&\n" +
	"\x10GetSKEvStatusReq\x12\x12\n" +
	"\x04EvId\x18\x01 \x01(\x03R\x04EvId\"R\n" +
	"\x11GetSKEvStatusResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\";\n" +
	"\x17ReduceSkProductStockReq\x12 \n" +
	"\vSKProductId\x18\x01 \x01(\x03R\vSKProductId\"A\n" +
	"\x18ReduceSkProductStockResp\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.product.BaseRespR\x04base2\x88\x05\n" +
	"\aProduct\x12F\n" +
	"\rCreateProduct\x12\x19.product.CreateProductReq\x1a\x1a.product.CreateProductResp\x12F\n" +
	"\rCreateSKEvent\x12\x19.product.CreateSKEventReq\x1a\x1a.product.CreateSKEventResp\x12L\n" +
	"\x0fCreateSKProduct\x12\x1b.product.CreateSKProductReq\x1a\x1c.product.CreateSKProductResp\x12C\n" +
	"\fGetSKProduct\x12\x18.product.GetSKProductReq\x1a\x19.product.GetSKProductResp\x12U\n" +
	"\x12GetSKEvStatusByPId\x12\x1e.product.GetSKEvStatusByPIdReq\x1a\x1f.product.GetSKEvStatusByPIdResp\x12F\n" +
	"\rGetSKEvStatus\x12\x19.product.GetSKEvStatusReq\x1a\x1a.product.GetSKEvStatusResp\x12[\n" +
	"\x14ReduceSkProductStock\x12 .product.ReduceSkProductStockReq\x1a!.product.ReduceSkProductStockResp\x12^\n" +
	"\x17ComReduceSkProductStock\x12 .product.ReduceSkProductStockReq\x1a!.product.ReduceSkProductStockRespB\x04Z\x02./b\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_product_proto_goTypes = []any{
	(*BaseResp)(nil),                 // 0: product.BaseResp
	(*CreateProductReq)(nil),         // 1: product.CreateProductReq
	(*CreateProductResp)(nil),        // 2: product.CreateProductResp
	(*CreateSKEventReq)(nil),         // 3: product.CreateSKEventReq
	(*CreateSKEventResp)(nil),        // 4: product.CreateSKEventResp
	(*CreateSKProductReq)(nil),       // 5: product.CreateSKProductReq
	(*CreateSKProductResp)(nil),      // 6: product.CreateSKProductResp
	(*SKProductInfo)(nil),            // 7: product.SKProductInfo
	(*GetSKProductReq)(nil),          // 8: product.GetSKProductReq
	(*GetSKProductResp)(nil),         // 9: product.GetSKProductResp
	(*GetSKEvStatusByPIdReq)(nil),    // 10: product.GetSKEvStatusByPIdReq
	(*GetSKEvStatusByPIdResp)(nil),   // 11: product.GetSKEvStatusByPIdResp
	(*GetSKEvStatusReq)(nil),         // 12: product.GetSKEvStatusReq
	(*GetSKEvStatusResp)(nil),        // 13: product.GetSKEvStatusResp
	(*ReduceSkProductStockReq)(nil),  // 14: product.ReduceSkProductStockReq
	(*ReduceSkProductStockResp)(nil), // 15: product.ReduceSkProductStockResp
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_product_proto_depIdxs = []int32{
	0,  // 0: product.CreateProductResp.base:type_name -> product.BaseResp
	16, // 1: product.CreateSKEventReq.start_time:type_name -> google.protobuf.Timestamp
	16, // 2: product.CreateSKEventReq.end_time:type_name -> google.protobuf.Timestamp
	0,  // 3: product.CreateSKEventResp.base:type_name -> product.BaseResp
	0,  // 4: product.CreateSKProductResp.base:type_name -> product.BaseResp
	0,  // 5: product.GetSKProductResp.base:type_name -> product.BaseResp
	7,  // 6: product.GetSKProductResp.info:type_name -> product.SKProductInfo
	0,  // 7: product.GetSKEvStatusByPIdResp.base:type_name -> product.BaseResp
	0,  // 8: product.GetSKEvStatusResp.base:type_name -> product.BaseResp
	0,  // 9: product.ReduceSkProductStockResp.base:type_name -> product.BaseResp
	1,  // 10: product.Product.CreateProduct:input_type -> product.CreateProductReq
	3,  // 11: product.Product.CreateSKEvent:input_type -> product.CreateSKEventReq
	5,  // 12: product.Product.CreateSKProduct:input_type -> product.CreateSKProductReq
	8,  // 13: product.Product.GetSKProduct:input_type -> product.GetSKProductReq
	10, // 14: product.Product.GetSKEvStatusByPId:input_type -> product.GetSKEvStatusByPIdReq
	12, // 15: product.Product.GetSKEvStatus:input_type -> product.GetSKEvStatusReq
	14, // 16: product.Product.ReduceSkProductStock:input_type -> product.ReduceSkProductStockReq
	14, // 17: product.Product.ComReduceSkProductStock:input_type -> product.ReduceSkProductStockReq
	2,  // 18: product.Product.CreateProduct:output_type -> product.CreateProductResp
	4,  // 19: product.Product.CreateSKEvent:output_type -> product.CreateSKEventResp
	6,  // 20: product.Product.CreateSKProduct:output_type -> product.CreateSKProductResp
	9,  // 21: product.Product.GetSKProduct:output_type -> product.GetSKProductResp
	11, // 22: product.Product.GetSKEvStatusByPId:output_type -> product.GetSKEvStatusByPIdResp
	13, // 23: product.Product.GetSKEvStatus:output_type -> product.GetSKEvStatusResp
	15, // 24: product.Product.ReduceSkProductStock:output_type -> product.ReduceSkProductStockResp
	15, // 25: product.Product.ComReduceSkProductStock:output_type -> product.ReduceSkProductStockResp
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
