// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: order_consumer.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_order_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_order_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_order_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_order_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_order_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_order_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_order_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_order_consumer_proto_rawDescGZIP(), []int{2}
}

type SetOrderHasPaidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderHasPaidReq) Reset() {
	*x = SetOrderHasPaidReq{}
	mi := &file_order_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderHasPaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderHasPaidReq) ProtoMessage() {}

func (x *SetOrderHasPaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderHasPaidReq.ProtoReflect.Descriptor instead.
func (*SetOrderHasPaidReq) Descriptor() ([]byte, []int) {
	return file_order_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *SetOrderHasPaidReq) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

type SetOrderHasPaidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderHasPaidResp) Reset() {
	*x = SetOrderHasPaidResp{}
	mi := &file_order_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderHasPaidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderHasPaidResp) ProtoMessage() {}

func (x *SetOrderHasPaidResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderHasPaidResp.ProtoReflect.Descriptor instead.
func (*SetOrderHasPaidResp) Descriptor() ([]byte, []int) {
	return file_order_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *SetOrderHasPaidResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_order_consumer_proto protoreflect.FileDescriptor

const file_order_consumer_proto_rawDesc = "" +
	"\n" +
	"\x14order_consumer.proto\x12\x0eorder_consumer\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x18\n" +
	"\x04Pong\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty\".\n" +
	"\x12SetOrderHasPaidReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\"C\n" +
	"\x13SetOrderHasPaidResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.order_consumer.BaseRespR\x04base2\xff\x01\n" +
	"\rOrderConsumer\x123\n" +
	"\x04Ping\x12\x15.order_consumer.Empty\x1a\x14.order_consumer.Pong\x12Z\n" +
	"\x0fSetOrderHasPaid\x12\".order_consumer.SetOrderHasPaidReq\x1a#.order_consumer.SetOrderHasPaidResp\x12]\n" +
	"\x12ComSetOrderHasPaid\x12\".order_consumer.SetOrderHasPaidReq\x1a#.order_consumer.SetOrderHasPaidRespB\x04Z\x02./b\x06proto3"

var (
	file_order_consumer_proto_rawDescOnce sync.Once
	file_order_consumer_proto_rawDescData []byte
)

func file_order_consumer_proto_rawDescGZIP() []byte {
	file_order_consumer_proto_rawDescOnce.Do(func() {
		file_order_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_consumer_proto_rawDesc), len(file_order_consumer_proto_rawDesc)))
	})
	return file_order_consumer_proto_rawDescData
}

var file_order_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_order_consumer_proto_goTypes = []any{
	(*BaseResp)(nil),            // 0: order_consumer.BaseResp
	(*Pong)(nil),                // 1: order_consumer.Pong
	(*Empty)(nil),               // 2: order_consumer.Empty
	(*SetOrderHasPaidReq)(nil),  // 3: order_consumer.SetOrderHasPaidReq
	(*SetOrderHasPaidResp)(nil), // 4: order_consumer.SetOrderHasPaidResp
}
var file_order_consumer_proto_depIdxs = []int32{
	0, // 0: order_consumer.SetOrderHasPaidResp.base:type_name -> order_consumer.BaseResp
	2, // 1: order_consumer.OrderConsumer.Ping:input_type -> order_consumer.Empty
	3, // 2: order_consumer.OrderConsumer.SetOrderHasPaid:input_type -> order_consumer.SetOrderHasPaidReq
	3, // 3: order_consumer.OrderConsumer.ComSetOrderHasPaid:input_type -> order_consumer.SetOrderHasPaidReq
	1, // 4: order_consumer.OrderConsumer.Ping:output_type -> order_consumer.Pong
	4, // 5: order_consumer.OrderConsumer.SetOrderHasPaid:output_type -> order_consumer.SetOrderHasPaidResp
	4, // 6: order_consumer.OrderConsumer.ComSetOrderHasPaid:output_type -> order_consumer.SetOrderHasPaidResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_consumer_proto_init() }
func file_order_consumer_proto_init() {
	if File_order_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_consumer_proto_rawDesc), len(file_order_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_consumer_proto_goTypes,
		DependencyIndexes: file_order_consumer_proto_depIdxs,
		MessageInfos:      file_order_consumer_proto_msgTypes,
	}.Build()
	File_order_consumer_proto = out.File
	file_order_consumer_proto_goTypes = nil
	file_order_consumer_proto_depIdxs = nil
}
