// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: payment.proto

package server

import (
	"context"

	"sk_mall/rpc/rpc_payment/internal/logic"
	"sk_mall/rpc/rpc_payment/internal/svc"
	"sk_mall/rpc/rpc_payment/types"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) PayOrder(ctx context.Context, in *__.PayOrderReq) (*__.PayOrderResp, error) {
	l := logic.NewPayOrderLogic(ctx, s.svcCtx)
	return l.PayOrder(in)
}

func (s *PaymentServer) SetPayLog(ctx context.Context, in *__.SetPayLogReq) (*__.SetPayLogResp, error) {
	l := logic.NewSetPayLogLogic(ctx, s.svcCtx)
	return l.SetPayLog(in)
}

func (s *PaymentServer) ComSetPayLog(ctx context.Context, in *__.SetPayLogReq) (*__.SetPayLogResp, error) {
	l := logic.NewComSetPayLogLogic(ctx, s.svcCtx)
	return l.ComSetPayLog(in)
}
