// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: merchant.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应
type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MerchantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Logo          []byte                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	LogoSuffix    string                 `protobuf:"bytes,3,opt,name=logoSuffix,proto3" json:"logoSuffix,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantInfo) Reset() {
	*x = MerchantInfo{}
	mi := &file_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfo) ProtoMessage() {}

func (x *MerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfo.ProtoReflect.Descriptor instead.
func (*MerchantInfo) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantInfo) GetLogo() []byte {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *MerchantInfo) GetLogoSuffix() string {
	if x != nil {
		return x.LogoSuffix
	}
	return ""
}

func (x *MerchantInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MerchantInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LegalName     string                 `protobuf:"bytes,1,opt,name=legalName,proto3" json:"legalName,omitempty"`
	IdCard        string                 `protobuf:"bytes,2,opt,name=idCard,proto3" json:"idCard,omitempty"`
	LicenseImg    []byte                 `protobuf:"bytes,3,opt,name=licenseImg,proto3" json:"licenseImg,omitempty"`
	LicenseSuffix string                 `protobuf:"bytes,4,opt,name=licenseSuffix,proto3" json:"licenseSuffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	mi := &file_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *AuthInfo) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *AuthInfo) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *AuthInfo) GetLicenseImg() []byte {
	if x != nil {
		return x.LicenseImg
	}
	return nil
}

func (x *AuthInfo) GetLicenseSuffix() string {
	if x != nil {
		return x.LicenseSuffix
	}
	return ""
}

type AccInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    uint64                 `protobuf:"varint,1,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	AccType       int32                  `protobuf:"varint,2,opt,name=accType,proto3" json:"accType,omitempty"`
	AccNo         string                 `protobuf:"bytes,3,opt,name=accNo,proto3" json:"accNo,omitempty"`
	AccName       string                 `protobuf:"bytes,4,opt,name=accName,proto3" json:"accName,omitempty"`
	BankName      string                 `protobuf:"bytes,5,opt,name=bankName,proto3" json:"bankName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccInfo) Reset() {
	*x = AccInfo{}
	mi := &file_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccInfo) ProtoMessage() {}

func (x *AccInfo) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccInfo.ProtoReflect.Descriptor instead.
func (*AccInfo) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *AccInfo) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *AccInfo) GetAccType() int32 {
	if x != nil {
		return x.AccType
	}
	return 0
}

func (x *AccInfo) GetAccNo() string {
	if x != nil {
		return x.AccNo
	}
	return ""
}

func (x *AccInfo) GetAccName() string {
	if x != nil {
		return x.AccName
	}
	return ""
}

func (x *AccInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

type CreateMerchantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MInfo         *MerchantInfo          `protobuf:"bytes,2,opt,name=MInfo,proto3" json:"MInfo,omitempty"`
	AInfo         *AuthInfo              `protobuf:"bytes,3,opt,name=AInfo,proto3" json:"AInfo,omitempty"`
	AcInfo        *AccInfo               `protobuf:"bytes,4,opt,name=AcInfo,proto3" json:"AcInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantReq) Reset() {
	*x = CreateMerchantReq{}
	mi := &file_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantReq) ProtoMessage() {}

func (x *CreateMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantReq.ProtoReflect.Descriptor instead.
func (*CreateMerchantReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMerchantReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMerchantReq) GetMInfo() *MerchantInfo {
	if x != nil {
		return x.MInfo
	}
	return nil
}

func (x *CreateMerchantReq) GetAInfo() *AuthInfo {
	if x != nil {
		return x.AInfo
	}
	return nil
}

func (x *CreateMerchantReq) GetAcInfo() *AccInfo {
	if x != nil {
		return x.AcInfo
	}
	return nil
}

type CreateMerchantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResp) Reset() {
	*x = CreateMerchantResp{}
	mi := &file_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResp) ProtoMessage() {}

func (x *CreateMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResp.ProtoReflect.Descriptor instead.
func (*CreateMerchantResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMerchantResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type GMerchantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    uint64                 `protobuf:"varint,1,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GMerchantInfo) Reset() {
	*x = GMerchantInfo{}
	mi := &file_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GMerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMerchantInfo) ProtoMessage() {}

func (x *GMerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMerchantInfo.ProtoReflect.Descriptor instead.
func (*GMerchantInfo) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *GMerchantInfo) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GMerchantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GMerchantInfo) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *GMerchantInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GMerchantInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GMerchantInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetMerchantByMIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    uint64                 `protobuf:"varint,1,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByMIdReq) Reset() {
	*x = GetMerchantByMIdReq{}
	mi := &file_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByMIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByMIdReq) ProtoMessage() {}

func (x *GetMerchantByMIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByMIdReq.ProtoReflect.Descriptor instead.
func (*GetMerchantByMIdReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchantByMIdReq) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type GetMerchantByMIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Info          *GMerchantInfo         `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByMIdResp) Reset() {
	*x = GetMerchantByMIdResp{}
	mi := &file_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByMIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByMIdResp) ProtoMessage() {}

func (x *GetMerchantByMIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByMIdResp.ProtoReflect.Descriptor instead.
func (*GetMerchantByMIdResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *GetMerchantByMIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetMerchantByMIdResp) GetInfo() *GMerchantInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetMerchantIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantIdReq) Reset() {
	*x = GetMerchantIdReq{}
	mi := &file_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantIdReq) ProtoMessage() {}

func (x *GetMerchantIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantIdReq.ProtoReflect.Descriptor instead.
func (*GetMerchantIdReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *GetMerchantIdReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMerchantIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	MId           uint64                 `protobuf:"varint,2,opt,name=mId,proto3" json:"mId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantIdResp) Reset() {
	*x = GetMerchantIdResp{}
	mi := &file_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantIdResp) ProtoMessage() {}

func (x *GetMerchantIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantIdResp.ProtoReflect.Descriptor instead.
func (*GetMerchantIdResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *GetMerchantIdResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetMerchantIdResp) GetMId() uint64 {
	if x != nil {
		return x.MId
	}
	return 0
}

type IncreaseBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       uint64                 `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"` //订单总金额
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseBalanceReq) Reset() {
	*x = IncreaseBalanceReq{}
	mi := &file_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseBalanceReq) ProtoMessage() {}

func (x *IncreaseBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseBalanceReq.ProtoReflect.Descriptor instead.
func (*IncreaseBalanceReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *IncreaseBalanceReq) GetOrderNo() uint64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *IncreaseBalanceReq) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *IncreaseBalanceReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type IncreaseBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseBalanceResp) Reset() {
	*x = IncreaseBalanceResp{}
	mi := &file_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseBalanceResp) ProtoMessage() {}

func (x *IncreaseBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseBalanceResp.ProtoReflect.Descriptor instead.
func (*IncreaseBalanceResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *IncreaseBalanceResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_merchant_proto protoreflect.FileDescriptor

const file_merchant_proto_rawDesc = "" +
	"\n" +
	"\x0emerchant.proto\x12\bmerchant\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xa4\x01\n" +
	"\fMerchantInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x02 \x01(\fR\x04logo\x12\x1e\n" +
	"\n" +
	"logoSuffix\x18\x03 \x01(\tR\n" +
	"logoSuffix\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\x86\x01\n" +
	"\bAuthInfo\x12\x1c\n" +
	"\tlegalName\x18\x01 \x01(\tR\tlegalName\x12\x16\n" +
	"\x06idCard\x18\x02 \x01(\tR\x06idCard\x12\x1e\n" +
	"\n" +
	"licenseImg\x18\x03 \x01(\fR\n" +
	"licenseImg\x12$\n" +
	"\rlicenseSuffix\x18\x04 \x01(\tR\rlicenseSuffix\"\x8f\x01\n" +
	"\aAccInfo\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x01 \x01(\x04R\n" +
	"merchantId\x12\x18\n" +
	"\aaccType\x18\x02 \x01(\x05R\aaccType\x12\x14\n" +
	"\x05accNo\x18\x03 \x01(\tR\x05accNo\x12\x18\n" +
	"\aaccName\x18\x04 \x01(\tR\aaccName\x12\x1a\n" +
	"\bbankName\x18\x05 \x01(\tR\bbankName\"\xae\x01\n" +
	"\x11CreateMerchantReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12,\n" +
	"\x05MInfo\x18\x02 \x01(\v2\x16.merchant.MerchantInfoR\x05MInfo\x12(\n" +
	"\x05AInfo\x18\x03 \x01(\v2\x12.merchant.AuthInfoR\x05AInfo\x12)\n" +
	"\x06AcInfo\x18\x04 \x01(\v2\x11.merchant.AccInfoR\x06AcInfo\"<\n" +
	"\x12CreateMerchantResp\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.merchant.BaseRespR\x04base\"\x97\x01\n" +
	"\rGMerchantInfo\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x01 \x01(\x04R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"5\n" +
	"\x13GetMerchantByMIdReq\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x01 \x01(\x04R\n" +
	"merchantId\"k\n" +
	"\x14GetMerchantByMIdResp\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.merchant.BaseRespR\x04base\x12+\n" +
	"\x04Info\x18\x02 \x01(\v2\x17.merchant.GMerchantInfoR\x04Info\"*\n" +
	"\x10GetMerchantIdReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"M\n" +
	"\x11GetMerchantIdResp\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.merchant.BaseRespR\x04base\x12\x10\n" +
	"\x03mId\x18\x02 \x01(\x04R\x03mId\"p\n" +
	"\x12IncreaseBalanceReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x04R\aorderNo\x12 \n" +
	"\vtotalAmount\x18\x02 \x01(\tR\vtotalAmount\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x03 \x01(\x03R\n" +
	"merchantId\"=\n" +
	"\x13IncreaseBalanceResp\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.merchant.BaseRespR\x04base2\x97\x03\n" +
	"\bMerchant\x12K\n" +
	"\x0eCreateMerchant\x12\x1b.merchant.CreateMerchantReq\x1a\x1c.merchant.CreateMerchantResp\x12Q\n" +
	"\x10GetMerchantByMId\x12\x1d.merchant.GetMerchantByMIdReq\x1a\x1e.merchant.GetMerchantByMIdResp\x12H\n" +
	"\rGetMerchantId\x12\x1a.merchant.GetMerchantIdReq\x1a\x1b.merchant.GetMerchantIdResp\x12N\n" +
	"\x0fIncreaseBalance\x12\x1c.merchant.IncreaseBalanceReq\x1a\x1d.merchant.IncreaseBalanceResp\x12Q\n" +
	"\x12ComIncreaseBalance\x12\x1c.merchant.IncreaseBalanceReq\x1a\x1d.merchant.IncreaseBalanceRespB\x04Z\x02./b\x06proto3"

var (
	file_merchant_proto_rawDescOnce sync.Once
	file_merchant_proto_rawDescData []byte
)

func file_merchant_proto_rawDescGZIP() []byte {
	file_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)))
	})
	return file_merchant_proto_rawDescData
}

var file_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_merchant_proto_goTypes = []any{
	(*BaseResp)(nil),             // 0: merchant.BaseResp
	(*MerchantInfo)(nil),         // 1: merchant.MerchantInfo
	(*AuthInfo)(nil),             // 2: merchant.AuthInfo
	(*AccInfo)(nil),              // 3: merchant.AccInfo
	(*CreateMerchantReq)(nil),    // 4: merchant.CreateMerchantReq
	(*CreateMerchantResp)(nil),   // 5: merchant.CreateMerchantResp
	(*GMerchantInfo)(nil),        // 6: merchant.GMerchantInfo
	(*GetMerchantByMIdReq)(nil),  // 7: merchant.GetMerchantByMIdReq
	(*GetMerchantByMIdResp)(nil), // 8: merchant.GetMerchantByMIdResp
	(*GetMerchantIdReq)(nil),     // 9: merchant.GetMerchantIdReq
	(*GetMerchantIdResp)(nil),    // 10: merchant.GetMerchantIdResp
	(*IncreaseBalanceReq)(nil),   // 11: merchant.IncreaseBalanceReq
	(*IncreaseBalanceResp)(nil),  // 12: merchant.IncreaseBalanceResp
}
var file_merchant_proto_depIdxs = []int32{
	1,  // 0: merchant.CreateMerchantReq.MInfo:type_name -> merchant.MerchantInfo
	2,  // 1: merchant.CreateMerchantReq.AInfo:type_name -> merchant.AuthInfo
	3,  // 2: merchant.CreateMerchantReq.AcInfo:type_name -> merchant.AccInfo
	0,  // 3: merchant.CreateMerchantResp.base:type_name -> merchant.BaseResp
	0,  // 4: merchant.GetMerchantByMIdResp.base:type_name -> merchant.BaseResp
	6,  // 5: merchant.GetMerchantByMIdResp.Info:type_name -> merchant.GMerchantInfo
	0,  // 6: merchant.GetMerchantIdResp.base:type_name -> merchant.BaseResp
	0,  // 7: merchant.IncreaseBalanceResp.base:type_name -> merchant.BaseResp
	4,  // 8: merchant.Merchant.CreateMerchant:input_type -> merchant.CreateMerchantReq
	7,  // 9: merchant.Merchant.GetMerchantByMId:input_type -> merchant.GetMerchantByMIdReq
	9,  // 10: merchant.Merchant.GetMerchantId:input_type -> merchant.GetMerchantIdReq
	11, // 11: merchant.Merchant.IncreaseBalance:input_type -> merchant.IncreaseBalanceReq
	11, // 12: merchant.Merchant.ComIncreaseBalance:input_type -> merchant.IncreaseBalanceReq
	5,  // 13: merchant.Merchant.CreateMerchant:output_type -> merchant.CreateMerchantResp
	8,  // 14: merchant.Merchant.GetMerchantByMId:output_type -> merchant.GetMerchantByMIdResp
	10, // 15: merchant.Merchant.GetMerchantId:output_type -> merchant.GetMerchantIdResp
	12, // 16: merchant.Merchant.IncreaseBalance:output_type -> merchant.IncreaseBalanceResp
	12, // 17: merchant.Merchant.ComIncreaseBalance:output_type -> merchant.IncreaseBalanceResp
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_merchant_proto_init() }
func file_merchant_proto_init() {
	if File_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_proto_depIdxs,
		MessageInfos:      file_merchant_proto_msgTypes,
	}.Build()
	File_merchant_proto = out.File
	file_merchant_proto_goTypes = nil
	file_merchant_proto_depIdxs = nil
}
