// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: cache_loader.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_cache_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_cache_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_cache_loader_proto_rawDescGZIP(), []int{0}
}

func (x *Pong) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cache_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cache_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cache_loader_proto_rawDescGZIP(), []int{1}
}

var File_cache_loader_proto protoreflect.FileDescriptor

const file_cache_loader_proto_rawDesc = "" +
	"\n" +
	"\x12cache_loader.proto\x12\fcache_loader\"\x18\n" +
	"\x04Pong\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty2>\n" +
	"\vCacheLoader\x12/\n" +
	"\x04Ping\x12\x13.cache_loader.Empty\x1a\x12.cache_loader.PongB\x04Z\x02./b\x06proto3"

var (
	file_cache_loader_proto_rawDescOnce sync.Once
	file_cache_loader_proto_rawDescData []byte
)

func file_cache_loader_proto_rawDescGZIP() []byte {
	file_cache_loader_proto_rawDescOnce.Do(func() {
		file_cache_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_loader_proto_rawDesc), len(file_cache_loader_proto_rawDesc)))
	})
	return file_cache_loader_proto_rawDescData
}

var file_cache_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cache_loader_proto_goTypes = []any{
	(*Pong)(nil),  // 0: cache_loader.Pong
	(*Empty)(nil), // 1: cache_loader.Empty
}
var file_cache_loader_proto_depIdxs = []int32{
	1, // 0: cache_loader.CacheLoader.Ping:input_type -> cache_loader.Empty
	0, // 1: cache_loader.CacheLoader.Ping:output_type -> cache_loader.Pong
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_loader_proto_init() }
func file_cache_loader_proto_init() {
	if File_cache_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_loader_proto_rawDesc), len(file_cache_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_loader_proto_goTypes,
		DependencyIndexes: file_cache_loader_proto_depIdxs,
		MessageInfos:      file_cache_loader_proto_msgTypes,
	}.Build()
	File_cache_loader_proto = out.File
	file_cache_loader_proto_goTypes = nil
	file_cache_loader_proto_depIdxs = nil
}
