// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: cache_loader.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheLoader_Ping_FullMethodName = "/cache_loader.CacheLoader/Ping"
)

// CacheLoaderClient is the client API for CacheLoader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheLoaderClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
}

type cacheLoaderClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheLoaderClient(cc grpc.ClientConnInterface) CacheLoaderClient {
	return &cacheLoaderClient{cc}
}

func (c *cacheLoaderClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, CacheLoader_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheLoaderServer is the server API for CacheLoader service.
// All implementations must embed UnimplementedCacheLoaderServer
// for forward compatibility.
type CacheLoaderServer interface {
	Ping(context.Context, *Empty) (*Pong, error)
	mustEmbedUnimplementedCacheLoaderServer()
}

// UnimplementedCacheLoaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheLoaderServer struct{}

func (UnimplementedCacheLoaderServer) Ping(context.Context, *Empty) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCacheLoaderServer) mustEmbedUnimplementedCacheLoaderServer() {}
func (UnimplementedCacheLoaderServer) testEmbeddedByValue()                     {}

// UnsafeCacheLoaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheLoaderServer will
// result in compilation errors.
type UnsafeCacheLoaderServer interface {
	mustEmbedUnimplementedCacheLoaderServer()
}

func RegisterCacheLoaderServer(s grpc.ServiceRegistrar, srv CacheLoaderServer) {
	// If the following call pancis, it indicates UnimplementedCacheLoaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheLoader_ServiceDesc, srv)
}

func _CacheLoader_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheLoaderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheLoader_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheLoaderServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheLoader_ServiceDesc is the grpc.ServiceDesc for CacheLoader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheLoader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache_loader.CacheLoader",
	HandlerType: (*CacheLoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CacheLoader_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache_loader.proto",
}
