// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: order.proto

package server

import (
	"context"

	"sk_mall/rpc/rpc_order/internal/logic"
	"sk_mall/rpc/rpc_order/internal/svc"
	"sk_mall/rpc/rpc_order/types"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) GetOrder(ctx context.Context, in *__.GetOrderReq) (*__.GetOrderResp, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderServer) GetOrderList(ctx context.Context, in *__.GetOrderListReq) (*__.GetOrderListResp, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}
