// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: cache_loader.proto

package server

import (
	"context"

	"sk_mall/rpc/cron/cache_loader/internal/logic"
	"sk_mall/rpc/cron/cache_loader/internal/svc"
	"sk_mall/rpc/cron/cache_loader/types"
)

type CacheLoaderServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCacheLoaderServer
}

func NewCacheLoaderServer(svcCtx *svc.ServiceContext) *CacheLoaderServer {
	return &CacheLoaderServer{
		svcCtx: svcCtx,
	}
}

func (s *CacheLoaderServer) Ping(ctx context.Context, in *__.Empty) (*__.Pong, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
