// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: seckill.proto

package server

import (
	"context"

	"sk_mall/rpc/rpc_seckill/internal/logic"
	"sk_mall/rpc/rpc_seckill/internal/svc"
	"sk_mall/rpc/rpc_seckill/types"
)

type SeckillServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedSeckillServer
}

func NewSeckillServer(svcCtx *svc.ServiceContext) *SeckillServer {
	return &SeckillServer{
		svcCtx: svcCtx,
	}
}

func (s *SeckillServer) CreateOrder(ctx context.Context, in *__.CreateOrderReq) (*__.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}
