// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: aggr_order.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_aggr_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddrInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddrId        int64                  `protobuf:"varint,1,opt,name=addrId,proto3" json:"addrId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrInfo) Reset() {
	*x = AddrInfo{}
	mi := &file_aggr_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfo) ProtoMessage() {}

func (x *AddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfo.ProtoReflect.Descriptor instead.
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{1}
}

func (x *AddrInfo) GetAddrId() int64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

type SkProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkProductId   int64                  `protobuf:"varint,1,opt,name=skProductId,proto3" json:"skProductId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkProductInfo) Reset() {
	*x = SkProductInfo{}
	mi := &file_aggr_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkProductInfo) ProtoMessage() {}

func (x *SkProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkProductInfo.ProtoReflect.Descriptor instead.
func (*SkProductInfo) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{2}
}

func (x *SkProductInfo) GetSkProductId() int64 {
	if x != nil {
		return x.SkProductId
	}
	return 0
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Addr          *AddrInfo              `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	SkProduck     *SkProductInfo         `protobuf:"bytes,3,opt,name=skProduck,proto3" json:"skProduck,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` //订单状态：0-待支付，1-已支付，2-已发货，3-已完成，4-已取消，5-超时关闭
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_aggr_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderInfo) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *OrderInfo) GetAddr() *AddrInfo {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *OrderInfo) GetSkProduck() *SkProductInfo {
	if x != nil {
		return x.SkProduck
	}
	return nil
}

func (x *OrderInfo) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderInfo) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *OrderInfo) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderInfo) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type GetOrderInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoReq) Reset() {
	*x = GetOrderInfoReq{}
	mi := &file_aggr_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReq) ProtoMessage() {}

func (x *GetOrderInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReq.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReq) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderInfoReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Info          *OrderInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoResp) Reset() {
	*x = GetOrderInfoResp{}
	mi := &file_aggr_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoResp) ProtoMessage() {}

func (x *GetOrderInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoResp.ProtoReflect.Descriptor instead.
func (*GetOrderInfoResp) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderInfoResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetOrderInfoResp) GetInfo() *OrderInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type OrderListElem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	SkProduck     *SkProductInfo         `protobuf:"bytes,2,opt,name=skProduck,proto3" json:"skProduck,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,4,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,5,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` //订单状态：0-待支付，1-已支付，2-已发货，3-已完成，4-已取消，5-超时关闭
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListElem) Reset() {
	*x = OrderListElem{}
	mi := &file_aggr_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListElem) ProtoMessage() {}

func (x *OrderListElem) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListElem.ProtoReflect.Descriptor instead.
func (*OrderListElem) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderListElem) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *OrderListElem) GetSkProduck() *SkProductInfo {
	if x != nil {
		return x.SkProduck
	}
	return nil
}

func (x *OrderListElem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderListElem) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *OrderListElem) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *OrderListElem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderListElem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderListElem) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type GetOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListReq) Reset() {
	*x = GetOrderListReq{}
	mi := &file_aggr_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListReq) ProtoMessage() {}

func (x *GetOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListReq.ProtoReflect.Descriptor instead.
func (*GetOrderListReq) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*OrderListElem       `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListResp) Reset() {
	*x = GetOrderListResp{}
	mi := &file_aggr_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListResp) ProtoMessage() {}

func (x *GetOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_aggr_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListResp.ProtoReflect.Descriptor instead.
func (*GetOrderListResp) Descriptor() ([]byte, []int) {
	return file_aggr_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderListResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetOrderListResp) GetList() []*OrderListElem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_aggr_order_proto protoreflect.FileDescriptor

const file_aggr_order_proto_rawDesc = "" +
	"\n" +
	"\x10aggr_order.proto\x12\taggrOrder\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\"\n" +
	"\bAddrInfo\x12\x16\n" +
	"\x06addrId\x18\x01 \x01(\x03R\x06addrId\"1\n" +
	"\rSkProductInfo\x12 \n" +
	"\vskProductId\x18\x01 \x01(\x03R\vskProductId\"\xee\x02\n" +
	"\tOrderInfo\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\x12'\n" +
	"\x04addr\x18\x02 \x01(\v2\x13.aggrOrder.AddrInfoR\x04addr\x126\n" +
	"\tskProduck\x18\x03 \x01(\v2\x18.aggrOrder.SkProductInfoR\tskProduck\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x05 \x01(\tR\tunitPrice\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\texpire_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"C\n" +
	"\x0fGetOrderInfoReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"e\n" +
	"\x10GetOrderInfoResp\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.aggrOrder.BaseRespR\x04base\x12(\n" +
	"\x04info\x18\x02 \x01(\v2\x14.aggrOrder.OrderInfoR\x04info\"\xc9\x02\n" +
	"\rOrderListElem\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\x126\n" +
	"\tskProduck\x18\x02 \x01(\v2\x18.aggrOrder.SkProductInfoR\tskProduck\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x04 \x01(\tR\tunitPrice\x12 \n" +
	"\vtotalAmount\x18\x05 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\texpire_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"S\n" +
	"\x0fGetOrderListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"i\n" +
	"\x10GetOrderListResp\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.aggrOrder.BaseRespR\x04base\x12,\n" +
	"\x04List\x18\x02 \x03(\v2\x18.aggrOrder.OrderListElemR\x04List2\x9d\x01\n" +
	"\taggrOrder\x12G\n" +
	"\fGetOrderInfo\x12\x1a.aggrOrder.GetOrderInfoReq\x1a\x1b.aggrOrder.GetOrderInfoResp\x12G\n" +
	"\fGetOrderList\x12\x1a.aggrOrder.GetOrderListReq\x1a\x1b.aggrOrder.GetOrderListRespB\x04Z\x02./b\x06proto3"

var (
	file_aggr_order_proto_rawDescOnce sync.Once
	file_aggr_order_proto_rawDescData []byte
)

func file_aggr_order_proto_rawDescGZIP() []byte {
	file_aggr_order_proto_rawDescOnce.Do(func() {
		file_aggr_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggr_order_proto_rawDesc), len(file_aggr_order_proto_rawDesc)))
	})
	return file_aggr_order_proto_rawDescData
}

var file_aggr_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_aggr_order_proto_goTypes = []any{
	(*BaseResp)(nil),              // 0: aggrOrder.BaseResp
	(*AddrInfo)(nil),              // 1: aggrOrder.AddrInfo
	(*SkProductInfo)(nil),         // 2: aggrOrder.SkProductInfo
	(*OrderInfo)(nil),             // 3: aggrOrder.OrderInfo
	(*GetOrderInfoReq)(nil),       // 4: aggrOrder.GetOrderInfoReq
	(*GetOrderInfoResp)(nil),      // 5: aggrOrder.GetOrderInfoResp
	(*OrderListElem)(nil),         // 6: aggrOrder.OrderListElem
	(*GetOrderListReq)(nil),       // 7: aggrOrder.GetOrderListReq
	(*GetOrderListResp)(nil),      // 8: aggrOrder.GetOrderListResp
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_aggr_order_proto_depIdxs = []int32{
	1,  // 0: aggrOrder.OrderInfo.addr:type_name -> aggrOrder.AddrInfo
	2,  // 1: aggrOrder.OrderInfo.skProduck:type_name -> aggrOrder.SkProductInfo
	9,  // 2: aggrOrder.OrderInfo.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: aggrOrder.OrderInfo.expire_at:type_name -> google.protobuf.Timestamp
	0,  // 4: aggrOrder.GetOrderInfoResp.base:type_name -> aggrOrder.BaseResp
	3,  // 5: aggrOrder.GetOrderInfoResp.info:type_name -> aggrOrder.OrderInfo
	2,  // 6: aggrOrder.OrderListElem.skProduck:type_name -> aggrOrder.SkProductInfo
	9,  // 7: aggrOrder.OrderListElem.created_at:type_name -> google.protobuf.Timestamp
	9,  // 8: aggrOrder.OrderListElem.expire_at:type_name -> google.protobuf.Timestamp
	0,  // 9: aggrOrder.GetOrderListResp.base:type_name -> aggrOrder.BaseResp
	6,  // 10: aggrOrder.GetOrderListResp.List:type_name -> aggrOrder.OrderListElem
	4,  // 11: aggrOrder.aggrOrder.GetOrderInfo:input_type -> aggrOrder.GetOrderInfoReq
	7,  // 12: aggrOrder.aggrOrder.GetOrderList:input_type -> aggrOrder.GetOrderListReq
	5,  // 13: aggrOrder.aggrOrder.GetOrderInfo:output_type -> aggrOrder.GetOrderInfoResp
	8,  // 14: aggrOrder.aggrOrder.GetOrderList:output_type -> aggrOrder.GetOrderListResp
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_aggr_order_proto_init() }
func file_aggr_order_proto_init() {
	if File_aggr_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggr_order_proto_rawDesc), len(file_aggr_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggr_order_proto_goTypes,
		DependencyIndexes: file_aggr_order_proto_depIdxs,
		MessageInfos:      file_aggr_order_proto_msgTypes,
	}.Build()
	File_aggr_order_proto = out.File
	file_aggr_order_proto_goTypes = nil
	file_aggr_order_proto_depIdxs = nil
}
