// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type EmailCodeReq struct {
	Email string `json:"email"`
}

type EmailCodeResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	NickName string `json:"nickname"`
	Token    string `json:"token"`
	Avatar   string `json:"avatar"`
}

type RegisterReq struct {
	UserInfo string `form:"userinfo"`
	Avatar   []byte `form:"-"`
	Suffix   string `form:"-"`
}

type RegisterResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
