// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateMerchantReq struct {
	JsonInfo       string `form:"info"`
	UserId         string `json:"-"`
	Logo           []byte `json:"-"`
	LogoSuffix     string `json:"-"`
	LincenseImg    []byte `json:"-"`
	LincenseSuffix string `json:"-"`
}

type CreateMerchantResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
