// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type GetOrderInfoReq struct {
	UserId  string
	OrderNo string `path:"no"`
}

type GetOrderInfoResp struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Info OrderInfo `json:"info"`
}

type GetOrderListReq struct {
	UserId string
	Page   int64 `form:"page"`
	Limit  int64 `form:"limit"`
}

type GetOrderListResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	List []OrderElem `json:"list"`
}
