// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type PayOrderReq struct {
	UserId  string `json:"-"`
	OrderNo string `json:"order_no"`
}

type PayOrderResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
