// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateEventReq struct {
	UserId    string `json:"-"`
	StartTime string `json:"s_time"`
	EndTime   string `json:"e_time"`
	Name      string `json:"name"`
}

type CreateEventResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CreateProductReq struct {
	JsonInfo    string `form:"info"`
	CoverImg    []byte
	CoverSuffix string
	UserId      string
}

type CreateProductResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CreateSkProductReq struct {
	UserId     string `json:"-"`
	EvId       string `json:"ev_id"`
	ProductId  string `json:"pro_id"`
	Price      string `json:"price"`
	Stock      string `json:"stock"`
	MerchantId string `json:"mer_id"`
}

type CreateSkProductResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetSkProductListReq struct {
	Key   string `form:"key"`
	Limit int64  `form:"limit"`
	Page  int64  `form:"page"`
}

type GetSkProductListResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	List []SkproductElem `json:"list"`
}
