// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateSkOrderReq struct {
	SKProductId string `json:"sk_pro_id"`
	UserId      string `json:"-"`
	AddrId      string `json:"addr_id"`
}

type CreateSkOrderResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
