// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Address struct {
	Name     string `json:"receiver_name"`
	Phone    string `json:"receiver_phone"`
	Province string `json:"province"`
	City     string `json:"city"`
	District string `json:"district"`
	Detail   string `json:"detail_address"`
	Default  int32  `json:"is_default"`
}

type AddressInfo struct {
	Id       string `json:"id"`
	Name     string `json:"receiver_name"`
	Phone    string `json:"receiver_phone"`
	Province string `json:"province"`
	City     string `json:"city"`
	District string `json:"district"`
	Detail   string `json:"detail_address"`
	Default  int32  `json:"is_default"`
}

type OrderAddr struct {
	AddrId string `json:"addr_id"`
}

type OrderElem struct {
	OrderNo     string       `json:"order_no"`
	Product     OrderProduct `json:"product"`
	Quantity    string       `json:"quantity"`
	UnitPrice   string       `json:"unit_price"`
	TotalAmount string       `json:"total_amount"`
	Status      int64        `json:"status"`
	CreateAt    string       `json:"create_at"`
	ExpireAt    string       `json:"expire_at"`
}

type OrderInfo struct {
	OrderNo     string       `json:"order_no"`
	Addr        OrderAddr    `json:"addr"`
	Product     OrderProduct `json:"product"`
	Quantity    string       `json:"quantity"`
	UnitPrice   string       `json:"unit_price"`
	TotalAmount string       `json:"total_amount"`
	Status      int64        `json:"status"`
	CreateAt    string       `json:"create_at"`
	ExpireAt    string       `json:"expire_at"`
}

type OrderProduct struct {
	SKProductId string `json:"sk_pro_id"`
}

type SkproductElem struct {
	EvId  string `json:"ev_id"`
	ProId string `json:"pro_id"`
	Stock int64  `json:"stock"`
	STime string `json:"s_time"`
	ETime string `json:"e_time"`
	Name  string `json:"name"`
	Desc  string `json:"desc"`
	Price string `json:"price"`
	Cover string `json:"cover"`
	Id    string `json:"id"`
}
