// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateAddrReq struct {
	UserId string  `json:"-"`
	Addr   Address `json:"addr"`
}

type CreateAddrResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteAddrReq struct {
	Id string `json:"id"`
}

type DeleteAddrResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetAddrsReq struct {
	Id string `json:"-"`
}

type GetAddrsResp struct {
	Code int           `json:"code"`
	Msg  string        `json:"msg"`
	List []AddressInfo `json:"list"`
}
