// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: aggr_order.proto

package server

import (
	"context"

	"sk_mall/rpc/aggr_order/internal/logic"
	"sk_mall/rpc/aggr_order/internal/svc"
	"sk_mall/rpc/aggr_order/types"
)

type AggrOrderServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedAggrOrderServer
}

func NewAggrOrderServer(svcCtx *svc.ServiceContext) *AggrOrderServer {
	return &AggrOrderServer{
		svcCtx: svcCtx,
	}
}

func (s *AggrOrderServer) GetOrderInfo(ctx context.Context, in *__.GetOrderInfoReq) (*__.GetOrderInfoResp, error) {
	l := logic.NewGetOrderInfoLogic(ctx, s.svcCtx)
	return l.GetOrderInfo(in)
}

func (s *AggrOrderServer) GetOrderList(ctx context.Context, in *__.GetOrderListReq) (*__.GetOrderListResp, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}
